name: Execute Cron Jobs

on:
  schedule:
    # Runs daily at specific times
    - cron: '0 6 * * *'
    - cron: '0 8 * * *'
    - cron: '0 10 * * *'
    - cron: '0 12 * * *'
    - cron: '0 16 * * *'
    - cron: '0 18 * * *'
  push:
    branches:
      - serverless # Replace with your default branch if needed

jobs:
  cron-jobs:
    runs-on: ubuntu-latest
    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      APP_ID: ${{ secrets.APP_ID }}
      BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
      ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      API_SECRET: ${{ secrets.API_SECRET }}
      API_KEY: ${{ secrets.API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.11.0

      - name: Install dependencies
        run: npm install

      - name: Run postLatestCtQuote job
        if: ${{ github.event_name == 'schedule' && github.event.schedule == '0 8 * * *' }}
        run: node -e "require('./configs/cronJobs').runPostLatestCtQuote()"

      - name: Run postGamblingQuote job
        if: ${{ github.event_name == 'schedule' && github.event.schedule == '0 12 * * *' }}
        run: node -e "require('./configs/cronJobs').runPostGamblingQuote()"

      - name: Run daily stats job
        if: ${{ github.event_name == 'schedule' && github.event.schedule == '0 16 * * *' }}
        run: node -e "require('./configs/cronJobs').runDailyStatsJob()"

      - name: Run postPerpsQuote job
        if: ${{ github.event_name == 'schedule' && github.event.schedule == '0 18 * * *' || github.event.schedule == '0 6 * * *' || github.event.schedule == '0 10 * * *' || github.event_name == 'push'}}
        run: node -e "require('./configs/cronJobs').runPostPerpsQuote()"

     
